In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv("book.csv")
df

Unnamed: 0  User.ID                                         Book.Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
...          ...      ...                                                ...   
9995        9996   162121       American Fried: Adventures of a Happy Eater.   
9996        9997   162121                              Cannibal In Manhattan   
9997        9998   162121                    How to Flirt: A Practical Guide   
9998        9999   162121                                           Twilight   
9999       10000   162129                       Kids Say the Darndest Things   

      Book.Rating  
0               5  
1               3  
2               6  
3               8  
4               6  
...           ...  
9995            7  
9996            9  
9997            7  
9998            8  
9999            6  

[10000 rows x 4 columns]

In [3]:
df.head()

Unnamed: 0  User.ID                                         Book.Title  \
0           1   276726                                Classical Mythology   
1           2   276729                                       Clara Callan   
2           3   276729                               Decision in Normandy   
3           4   276736  Flu: The Story of the Great Influenza Pandemic...   
4           5   276737                             The Mummies of Urumchi   

   Book.Rating  
0            5  
1            3  
2            6  
3            8  
4            6

In [4]:
df.rename(columns = {'User.ID':'User_ID','Book.Title':'Book_Title', 'Book.Rating':'Book_Rating'}, inplace = True)
df
   

Unnamed: 0  User_ID                                         Book_Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
...          ...      ...                                                ...   
9995        9996   162121       American Fried: Adventures of a Happy Eater.   
9996        9997   162121                              Cannibal In Manhattan   
9997        9998   162121                    How to Flirt: A Practical Guide   
9998        9999   162121                                           Twilight   
9999       10000   162129                       Kids Say the Darndest Things   

      Book_Rating  
0               5  
1               3  
2               6  
3               8  
4               6  
...           ...  
9995            7  
9996            9  
9997            7  
9998            8  
9999            6  

[10000 rows x 4 columns]

#  it is required to change the column name as Book.Rating has . which cause problem in many command so we replaced. with _

In [5]:
# number of unique users in the dataset
len(df['User_ID'].unique())

2182

In [6]:
# number of unique books in the dataset
len(df['Book_Title'].unique())

9659

In [7]:
#Create important columns for recommendation engine
columns = ['User_ID','Book_Title','Book_Rating']

In [8]:
df[columns]

User_ID                                         Book_Title  Book_Rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
...       ...                                                ...          ...
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8
9999   162129                       Kids Say the Darndest Things            6

[10000 rows x 3 columns]

In [9]:
df[columns].isnull().sum()

User_ID        0
Book_Title     0
Book_Rating    0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   10000 non-null  int64 
 1   User_ID      10000 non-null  int64 
 2   Book_Title   10000 non-null  object
 3   Book_Rating  10000 non-null  int64 
dtypes: int64(3), object(1)
memory usage: 312.6+ KB


# user id and book rating are numeric while book.Title is object so we can not apply +(add) , first we convert it into string

In [11]:
df['User_ID'] = df['User_ID'].apply(str)

In [12]:
df['Book_Rating'] = df['Book_Rating'].apply(str)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   10000 non-null  int64 
 1   User_ID      10000 non-null  object
 2   Book_Title   10000 non-null  object
 3   Book_Rating  10000 non-null  object
dtypes: int64(1), object(3)
memory usage: 312.6+ KB


In [14]:
def get_important_features(data):
    important_features = []
    for i in range(data.shape[0]):
        a = (data["User_ID"][i]+' '+data["Book_Title"][i]+' '+data["Book_Rating"][i])
        important_features.append(a)
        
    return important_features

In [15]:
df_clean = df[columns]

In [16]:
df_clean["important_features"] = get_important_features(df_clean) #  above defined function get_important_features(data) with
# return function
df_clean

User_ID                                         Book_Title Book_Rating  \
0     276726                                Classical Mythology           5   
1     276729                                       Clara Callan           3   
2     276729                               Decision in Normandy           6   
3     276736  Flu: The Story of the Great Influenza Pandemic...           8   
4     276737                             The Mummies of Urumchi           6   
...      ...                                                ...         ...   
9995  162121       American Fried: Adventures of a Happy Eater.           7   
9996  162121                              Cannibal In Manhattan           9   
9997  162121                    How to Flirt: A Practical Guide           7   
9998  162121                                           Twilight           8   
9999  162129                       Kids Say the Darndest Things           6   

                                     important_features  
0                          276726 Classical Mythology 5  
1                                 276729 Clara Callan 3  
2                         276729 Decision in Normandy 6  
3     276736 Flu: The Story of the Great Influenza P...  
4                       276737 The Mummies of Urumchi 6  
...                                                 ...  
9995  162121 American Fried: Adventures of a Happy E...  
9996                     162121 Cannibal In Manhattan 9  
9997           162121 How to Flirt: A Practical Guide 7  
9998                                  162121 Twilight 8  
9999              162129 Kids Say the Darndest Things 6  

[10000 rows x 4 columns]

In [17]:
#Convert text into matrix
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer


cm = CountVectorizer().fit_transform(df_clean["important_features"])

In [18]:
# countvectorizer is used to make vector matrix of each  unique words (from a given text) with their frequency....
 # but in index form as the code of unique words

In [19]:
# CountVectorizer makes new columns having new words in column "important_features

In [20]:
cm.toarray().shape


(10000, 13743)

In [21]:
cm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
cm

<10000x13743 sparse matrix of type '<class 'numpy.int64'>'
	with 63985 stored elements in Compressed Sparse Row format>

In [23]:
cs = cosine_similarity(cm) # one book compare with all other book , very similar to corelation .corr() of numerical columns

In [24]:
cs.shape

(10000, 10000)

In [25]:
cs

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.28867513, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.28867513, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.28867513,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.28867513, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [26]:
book1= 'Decision in Normandy'

In [27]:
book_id = df_clean[df_clean['Book_Title']==book1]
book_id

User_ID            Book_Title Book_Rating             important_features
2  276729  Decision in Normandy           6  276729 Decision in Normandy 6

In [28]:
book_id = df_clean[df_clean['Book_Title']==book1].index.values[0]
book_id

2

In [29]:
cs[2]

array([0.        , 0.28867513, 1.        , ..., 0.        , 0.        ,
       0.        ])

In [30]:
cs[book_id]

array([0.        , 0.28867513, 1.        , ..., 0.        , 0.        ,
       0.        ])

# score = list(enumerate(cs[book_id])) # enumerate function adds the index (counting) with the iterable object  cs accepts only number so first convert book_id into index(number)


In [31]:
score = list(enumerate(cs[book_id])) 

In [32]:
score

[(0, 0.0),
 (1, 0.2886751345948129),
 (2, 1.0),
 (3, 0.0),
 (4, 0.0),
 (5, 0.0),
 (6, 0.0),
 (7, 0.0),
 (8, 0.0),
 (9, 0.0),
 (10, 0.0),
 (11, 0.0),
 (12, 0.0),
 (13, 0.0),
 (14, 0.0),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.0),
 (20, 0.0),
 (21, 0.0),
 (22, 0.0),
 (23, 0.11180339887498948),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.0),
 (28, 0.0),
 (29, 0.0),
 (30, 0.0),
 (31, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (36, 0.0),
 (37, 0.0),
 (38, 0.0),
 (39, 0.25),
 (40, 0.0),
 (41, 0.0),
 (42, 0.0),
 (43, 0.0),
 (44, 0.0),
 (45, 0.0),
 (46, 0.0),
 (47, 0.0),
 (48, 0.25),
 (49, 0.0),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.0),
 (55, 0.0),
 (56, 0.0),
 (57, 0.0),
 (58, 0.0),
 (59, 0.0),
 (60, 0.0),
 (61, 0.0),
 (62, 0.0),
 (63, 0.0),
 (64, 0.0),
 (65, 0.0),
 (66, 0.0),
 (67, 0.0),
 (68, 0.0),
 (69, 0.0),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (73, 0.0),
 (74, 0.0),
 (75, 0.0),
 (76, 0.0),
 (77, 0.0),
 (78, 0.14433756729740646),
 (79, 0.0),
 

In [33]:
sorted_scores = sorted(score,key=lambda x:x[1],reverse =True) #Return a new list containing all items from the iterable 
# in ascending order.


In [34]:
sorted_scores

[(2, 1.0),
 (7223, 0.3333333333333333),
 (2641, 0.31622776601683794),
 (8471, 0.31622776601683794),
 (717, 0.30151134457776363),
 (1, 0.2886751345948129),
 (3550, 0.2886751345948129),
 (4098, 0.2886751345948129),
 (5258, 0.2886751345948129),
 (6499, 0.2886751345948129),
 (5484, 0.2672612419124244),
 (9666, 0.2672612419124244),
 (1168, 0.2581988897471611),
 (5382, 0.2581988897471611),
 (39, 0.25),
 (48, 0.25),
 (247, 0.25),
 (302, 0.25),
 (573, 0.25),
 (665, 0.25),
 (1159, 0.25),
 (1293, 0.25),
 (1336, 0.25),
 (1355, 0.25),
 (1496, 0.25),
 (1612, 0.25),
 (1896, 0.25),
 (2033, 0.25),
 (2190, 0.25),
 (2292, 0.25),
 (2465, 0.25),
 (2543, 0.25),
 (2916, 0.25),
 (2975, 0.25),
 (3163, 0.25),
 (3201, 0.25),
 (3754, 0.25),
 (3779, 0.25),
 (4133, 0.25),
 (4138, 0.25),
 (4797, 0.25),
 (4826, 0.25),
 (4941, 0.25),
 (5290, 0.25),
 (5413, 0.25),
 (5988, 0.25),
 (6006, 0.25),
 (6051, 0.25),
 (6228, 0.25),
 (6366, 0.25),
 (6656, 0.25),
 (6740, 0.25),
 (6938, 0.25),
 (6966, 0.25),
 (7139, 0.25),
 (7172

In [35]:
sorted_scores[1:]# removing the 0 th row that means removing the same book id or book name

[(7223, 0.3333333333333333),
 (2641, 0.31622776601683794),
 (8471, 0.31622776601683794),
 (717, 0.30151134457776363),
 (1, 0.2886751345948129),
 (3550, 0.2886751345948129),
 (4098, 0.2886751345948129),
 (5258, 0.2886751345948129),
 (6499, 0.2886751345948129),
 (5484, 0.2672612419124244),
 (9666, 0.2672612419124244),
 (1168, 0.2581988897471611),
 (5382, 0.2581988897471611),
 (39, 0.25),
 (48, 0.25),
 (247, 0.25),
 (302, 0.25),
 (573, 0.25),
 (665, 0.25),
 (1159, 0.25),
 (1293, 0.25),
 (1336, 0.25),
 (1355, 0.25),
 (1496, 0.25),
 (1612, 0.25),
 (1896, 0.25),
 (2033, 0.25),
 (2190, 0.25),
 (2292, 0.25),
 (2465, 0.25),
 (2543, 0.25),
 (2916, 0.25),
 (2975, 0.25),
 (3163, 0.25),
 (3201, 0.25),
 (3754, 0.25),
 (3779, 0.25),
 (4133, 0.25),
 (4138, 0.25),
 (4797, 0.25),
 (4826, 0.25),
 (4941, 0.25),
 (5290, 0.25),
 (5413, 0.25),
 (5988, 0.25),
 (6006, 0.25),
 (6051, 0.25),
 (6228, 0.25),
 (6366, 0.25),
 (6656, 0.25),
 (6740, 0.25),
 (6938, 0.25),
 (6966, 0.25),
 (7139, 0.25),
 (7172, 0.25),
 (

In [38]:
j = 0
print("The 7 most recommended movies to ",book1,"are:\n")

for item in sorted_scores[1:]:
    book_title = df_clean[df_clean.index ==item[0]]['Book_Title'].values[0]
    print(j+1,book_title)
    j = j+1
    if j>6:
        break

The 7 most recommended movies to  Decision in Normandy are:

1 In guten wie in schlechten Tagen.
2 Reading Lolita in Tehran: A Memoir in Books
3 Why in the World: Adventures in Geography
4 Lost in Place: Growing Up Absurd in Suburbia
5 Clara Callan
6 Going in
7 In Rajasthan
